#Data Sayns va Sunʼiy Intellekt Praktikum

#NumPy kutubxonasi boʻyicha amaliy vazifa


#### 1. NumPy kutubxonasini `np` nomi ostida yuklash va uni chop etish.

Versiya va konfiguratsiyani tekshirish.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np


#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantirish.

`💡Ishora` numpy.array

In [ ]:
data = [1,2,3,4,5]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz oʻlchovli massiv yaratish.



`💡Ishora` np.zeros

In [ ]:
arr2 = np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 4. Massiv yaratish va uning xotira hajmini topish.



`💡Ishora` size, itemsize

In [ ]:
arr3 = np.arange(10)
print(arr3.size)
print(arr3.itemsize)


10
8


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [ ]:
np.add?

In [ ]:
np.add??

#### 6. Shunday vekor yaratishki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [ ]:
import numpy as np
arr4 = np.zeros((3,4))
arr4[1,1] = 1
arr4

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yaratish.



`💡Ishora` arange

In [ ]:
arr5 = np.arange(20,59)
arr5

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari oʻzgartirish, (birinchi element oxirgisi boʻladi)



`💡Ishora` array[::-1]

In [ ]:
import numpy as np
arr6 = np.array([1,2,3,4,5])
rev_arr = arr6[::-1]
print(arr6)
print(rev_arr)

[1 2 3 4 5]
[5 4 3 2 1]


#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yaratish.


`💡Ishora` reshape

In [ ]:
a = np.arange(12,21)
b = a.reshape(3, 3)       # 3 qator, 3 ustun

print( a)
print( b)


[12 13 14 15 16 17 18 19 20]
[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini topish.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
import numpy as np

a = np.array([3, 7, 0, 0, 9, 0])
zero_indices = np.where(a == 0)[0]

print(zero_indices)

[2 3 5]


#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yaratish.


`💡Ishora` np.random.random

In [ ]:
arrs = np.random.randn(2,2)
arrs

array([[-0.1934509 ,  1.27925819],
       [-0.29426018, -0.15255387]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yaratish. Soʻng uning eng katta va eng kichik qiymatlarini topish.


`💡Ishora` min, max

In [ ]:
arr9 = np.random.randn(9,9)
print(arr9)
print(arr9.max())
print(arr9.min())

[[-0.19091971 -0.44275125  0.3137879   0.02877039 -1.55311678 -0.2032847
  -0.42940126 -0.77994534  0.01638374]
 [-1.0089337   2.03794333  0.79036214 -0.01429001 -0.27209225  0.32867858
   0.28172319  0.60815583 -0.05635523]
 [-1.68615195 -0.42628157 -1.25223081  0.05351573  0.88030074 -1.72248708
  -0.30202486 -1.62683123  0.35300817]
 [ 0.30818584 -0.87290962 -0.11929937  0.64801008 -1.24591189 -0.48282673
  -0.07159646  0.98032448  0.46605543]
 [ 0.44858893  0.11185342  0.41634239 -0.09983958 -0.97240809  2.19788164
  -0.15028275  0.80371959  0.79692922]
 [-1.03951556 -0.23971505 -0.53253689 -0.40739925 -0.1200513  -0.45586881
   1.18908792 -2.02895153 -1.34266405]
 [-1.80015099 -0.208623    0.40999512  0.53046236  1.57887    -0.71195158
  -1.33323824 -0.603198   -1.82133784]
 [ 0.44295107  0.7562335   2.0271685   0.9885621  -1.19283255 -0.73164042
   0.61685667 -0.80840198  0.80417335]
 [ 0.10233129 -1.16475978  1.55559605 -1.62308055  0.24243916 -0.63737116
  -0.31555789  0.437197

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
True
False
nan
Floating point xatoligi sabab False chiqadi
NaN bilan hisoblash natijasi nan
Tenglik har doim False, chunki NaN o‘ziga teng emas
in operatori obyekt manzilini tekshiradi, shuning uchun True

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yaratish, soʻng ularning  koʻpaytmasini hisoblash.



`💡Ishora` np.dot` or `np.ones

In [ ]:
A = np.ones((6, 3))
B = np.ones((3, 4))
C = np.dot(A, B)
print("A =", A)
print("B =", B)
print("C =", C)

A = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
C = [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5), -1))  #→ 9  #sum(range(5), -1) → bu degani: 0+1+2+3+4 = 10, keyin + (-1) qo‘shiladi.
# Built-in sum
print(sum(range(5), -1))  #→ 10  # NumPy sum (axboriy o‘cham bo‘yicha yig‘adi)

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtirish va ular usida quyidagi amallarni bajarish.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])

print("Array a:", a)
print("Array b:", b)

print("a > b :", a > b)      # [False False]
print("a >= b:", a >= b)     # [False False]
print("a < b :", a < b)      # [ True  True]
print("a <= b:", a <= b)     # [ True  True]

Array a: [1 2]
Array b: [4 5]
a > b : [False False]
a >= b: [False False]
a < b : [ True  True]
a <= b: [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))        # NaN (0 bo‘linmoqda 0ga — matematik jihatdan aniqlanmagan)
print(np.array(0) // np.array(0))       # Warning + 0 (Integer bo‘linma — 0ga bo‘lish xatolik beradi)
print(np.array([np.nan]).astype(int).astype(float))  # np.nan ni int ga o‘girganda u katta manfiy son (-9223372036854775808) ga aylanadi, so‘ng float ko‘rinishida chiqariladi.

#### 18. Ikkita massiv yaratish va ular orasidagi umumiy qiymatlarni topish.


`💡Ishora` np.intersect1d

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

common = np.intersect1d(a, b)

print("Array a:", a)
print("Array b:", b)
print("Umumiy elementlar:", common)

Array a: [1 2 3 4]
Array b: [3 4 5 6]
Umumiy elementlar: [3 4]


#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yaratish, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib olish.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
import numpy as np

# Tasodifiy sonlardan iborat massiv (musbat sonlar, 0 dan 10 gacha)
arr = np.random.uniform(0, 10, 5)
print("Asl massiv:", arr)

# 1-usul: %
print("1-usul (% bilan):", arr - arr % 1)

# 2-usul: np.floor
print("2-usul (np.floor):", np.floor(arr))

# 3-usul: astype(int)
print("3-usul (astype(int)):", arr.astype(int))

# 4-usul: np.trunc
print("4-usul (np.trunc):", np.trunc(arr))

Asl massiv: [9.433365   9.04406909 2.37556531 4.55823938 6.728984  ]
1-usul (% bilan): [9. 9. 2. 4. 6.]
2-usul (np.floor): [9. 9. 2. 4. 6.]
3-usul (astype(int)): [9 9 2 4 6]
4-usul (np.trunc): [9. 9. 2. 4. 6.]


#### 20. Oʻlchovlari 3x3 matritsa yaratish, ularning qator qiymatlari 0 dan 2 gacha boʻladi.



`💡Ishora` np.arange

In [ ]:
mat = np.tile(np.arange(3), (3, 1))
mat

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yaratish va uni oʻsish tartibida chiqaruvchi dastur tuzish.



`💡Ishora` sort

In [ ]:
arr = np.random.rand(10)
arr

array([0.17545177, 0.72536784, 0.92773537, 0.59961757, 0.82816173,
       0.52825238, 0.1626429 , 0.26635618, 0.76357972, 0.71592993])

In [ ]:
arr.sort()
arr

array([0.1626429 , 0.17545177, 0.26635618, 0.52825238, 0.59961757,
       0.71592993, 0.72536784, 0.76357972, 0.82816173, 0.92773537])

#### 22. Ikki tasodifiy A va B massiv yaratish, ularning tengligini tekshirish.

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A = np.random.rand(3, 3)
B = A.copy() + 1e-8  # juda kichik farq

print("A:\n", A)
print("B:\n", B)

print("np.array_equal(A, B):", np.array_equal(A, B))

print("np.allclose(A, B):", np.allclose(A, B))  # np.allclose – juda kichik farqlar (epsilon) bo‘lsa
                                                  # ham yaqin deb hisoblaydi (ya’ni almost equal).

A:
 [[0.0657768  0.58184108 0.561797  ]
 [0.16400097 0.86620353 0.48740945]
 [0.69336881 0.3455509  0.97081684]]
B:
 [[0.06577681 0.58184109 0.56179701]
 [0.16400098 0.86620354 0.48740946]
 [0.69336882 0.34555091 0.97081685]]
np.array_equal(A, B): False
np.allclose(A, B): True


#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzish va ularni oʻzaro koʻpaytirish.


`💡Ishora` np.dot or np.ones

In [ ]:
A = np.ones((6, 3))
B = np.ones((3, 4))
C = np.dot(A, B)
print("A =", A)
print("B =", B)
print("C =", C)

A = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
C = [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yaratish, soʻng uning eng katta qiymatini 0 ga oʻzgartirish.


`💡Ishora` argmax

In [ ]:
a = np.random.rand(5)
print(a)

max_index = a.argmax()
a[max_index] = 0

print("1ta max qiymatni 0 ga almashtirildi:", a)

[0.36512057 0.09671186 0.79610272 0.05168926 0.42517684]
1ta max qiymatni 0 ga almashtirildi: [0.36512057 0.09671186 0.         0.05168926 0.42517684]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlash.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
bugun = np.datetime64('today')
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')

print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)

Kecha: 2025-07-20
Bugun: 2025-07-21
Ertaga: 2025-07-22


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlash.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
yanvar_sanalar = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
print("2016-yil yanvar sanalari:")
print(yanvar_sanalar)

2016-yil yanvar sanalari:
['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib olish.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
import numpy as np

# Tasodifiy sonlardan iborat massiv (musbat sonlar, 0 dan 10 gacha)
arr = np.random.uniform(0, 10, 5)
print("Asl massiv:", arr)

# 1-usul: %
print("1-usul (% bilan):", arr - arr % 1)

# 2-usul: np.floor
print("2-usul (np.floor):", np.floor(arr))

# 3-usul: astype(int)
print("3-usul (astype(int)):", arr.astype(int))

# 4-usul: np.trunc
print("4-usul (np.trunc):", np.trunc(arr))

Asl massiv: [1.87215015 0.35391732 4.65522135 3.62531793 4.0978395 ]
1-usul (% bilan): [1. 0. 4. 3. 4.]
2-usul (np.floor): [1. 0. 4. 3. 4.]
3-usul (astype(int)): [1 0 4 3 4]
4-usul (np.trunc): [1. 0. 4. 3. 4.]


28. Ixtiyoriy kichik massivlar yaratish, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzish.


`💡Ishora` np.add.reduce

In [ ]:
a = np.array([1, 2, 3, 4, 5])

# Oddiy yig'indi
print("np.sum:", np.sum(a))


np.sum: 15


In [ ]:
# Tezroq usul - reduce orqali
np.add.reduce(a)


np.int64(15)

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzish.


`💡Ishora` array[::4]

In [ ]:
a = np.array([1, 2, 3, 4, 5])

result = np.zeros(len(a) + (len(a)-1)*3, dtype=int)

result[::4] = a

print("Natija:", result)

Natija: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olamizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
from numpy.lib.stride_tricks import as_strided

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window_size = 4

# Har bir element hajmi (baytda)
stride = a.strides[0]

# Yangi shakl va strides
b = as_strided(a, shape=(len(a)-window_size+1, window_size), strides=(stride, stride))

print("b matritsa:\n", b)

b matritsa:
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yaratish, unga oʻxshash qiymatlar kiritish. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzish.


`💡Ishora` np.bincount, argmax

In [ ]:
arr = np.array([4, 7, 2, 7, 9, 4, 3, 2, 2])

# Har bir qiymat necha marta qatnashganini hisoblaydi (indekslar sonlarning o‘zlari bo‘ladi)
counts = np.bincount(arr)

# Eng ko‘p uchragan qiymatni topamiz
most_common = np.argmax(counts)

print("Eng ko‘p uchragan qiymat:", most_common)
print("Necha marta:", counts[most_common])

Eng ko‘p uchragan qiymat: 2
Necha marta: 3
